Repository 202306-NEA-DZ-FEW/Capstone-Dream-Team, pull requests merged in 2023-11, with the labels that each got.

#65 57 modal
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/History/Adminhistory.jsx
  src/components/History/Historybar.jsx
  src/components/History/Historycard.jsx
Labels: feature, component

#69 57 modal
  src/components/Cart/addToCartButton.jsx
  src/components/Cart/card.jsx
  src/components/meal/mealcard.jsx
  src/components/meal/meals.jsx
  src/components/meal/modal.jsx
  src/pages/cart/index.jsx
Labels: bug, component

#70 57 modal
  src/components/Cart/addToCartButton.jsx
  src/components/Cart/card.jsx
  src/components/Cart/checkout.jsx
  src/components/meal/mealcard.jsx
  src/components/meal/meals.jsx
  src/components/meal/modal.jsx
  src/pages/cart/index.jsx
Labels: component, hard, data

#73 fix: fix fetch data in some components
  src/components/Cart/addToCartButton.jsx
  src/components/Cart/checkout.jsx
  src/components/Sidemenu.jsx
  src/components/meal/modal.jsx
  src/pages/admin-dashboard/index.js
  src/pages/cart/index.jsx
Labels: bug, page, component, data

#75 57 modal
  package-lock.json
  package.json
  src/components/Cart/StripeContainer.js
  src/components/Cart/checkout.js
  src/pages/_app.jsx
  src/pages/api/create-payment-intent.js
  src/pages/cart/index.jsx
Labels: component, hard, data

#76 57 modal
  src/components/Cart/checkout.js
  src/components/History/Historycard.jsx
  src/pages/api/create-payment-intent.js
Labels: component, data

#78 77 handle quantity
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Auth/signUp.jsx
  src/components/Cart/addToCartButton.jsx
  src/components/Cart/card.jsx
  src/components/Settings.jsx
  src/components/meal/mealcard.jsx
  src/components/meal/meals.jsx
  src/components/meal/modal.jsx
  src/pages/cart/index.jsx
Labels: data

#82 feat(admin dashboard sidemenu): add toggle button in small size screens
  src/components/Sidemenu.jsx
  src/pages/admin-dashboard/index.js
Labels: feature, Medium

#88 Feat/homepage
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Cart/cartIcon.jsx
  src/components/Footer.jsx
  src/components/Home/Joinus.jsx
  src/components/Home/Navbar.jsx
  src/components/Home/Restaurant.jsx
  src/components/Home/Slider.jsx
  src/components/Home/Sponsors.jsx
  src/components/Home/__test__/__snapshots__/Slider.test.jsx.snap
  src/pages/index.jsx
Labels: feature, Medium

#90 style meals section
  src/components/Add-meals.jsx
  src/components/AddMeals/Add-meals.jsx
  src/components/Meals/addMeals.jsx
  src/components/Meals/mealsTable.jsx
  src/components/Sidemenu.jsx
Labels: page, component, data, style

#91 85 meals section
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Auth/__test__/__snapshots__/signUp.test.js.snap
  src/components/Auth/__test__/signUp.test.js
  src/components/Auth/signUp.jsx
  src/components/Meals/addMeals.jsx
  src/components/Meals/mealsTable.jsx
  src/pages/admin-dashboard/index.js
Labels: bug, component, style

#97 updated the checkout and created the about us page
  public/images/aboutus/bouchra.png
  public/images/aboutus/buymeameal.png
  public/images/aboutus/create.png
  public/images/aboutus/firebase.png
  public/images/aboutus/firebase.svg
  public/images/aboutus/lamp.svg
  public/images/aboutus/materials.png
  public/images/aboutus/mounib.jpeg
  public/images/aboutus/recoded.png
  public/images/aboutus/responsive (1).svg
  public/images/aboutus/responsive.svg
  public/images/aboutus/rsp.png
  public/images/meals/142.jpg
  public/images/meals/143.jpg
  public/images/meals/169.jpg
  public/images/meals/Image (20).png
  public/images/meals/Image 234.png
  public/images/meals/Image104.png
  public/images/meals/Image19.png
  public/images/meals/Image218.png
  public/images/meals/Image224.png
  public/images/meals/Image50.png
  public/images/meals/bolognese-sauce-pasta-salad-italian-cuisine-spaghetti-cooking-thumbnail.jpg
  public/images/meals/italian-cuisine-pasta-organic-food-restaurant-foods.jpg
  public/locales/en/common.json
  src/components/Cart/addToCartButton.jsx
  src/components/Cart/card.jsx
  src/components/Cart/checkout.jsx
  src/components/History/Adminhistory.jsx
  src/components/History/History.jsx
  src/components/History/Historybar.jsx
  src/components/History/Historycard.jsx
  src/components/History/__test__/Adminhistory.test.jsx
  src/components/History/__test__/Historybar.test.jsx
  src/components/History/__test__/Historycard.test.jsx
  src/components/History/__test__/__snapshots__/Adminhistory.test.jsx.snap
  src/components/History/__test__/__snapshots__/Historybar.test.jsx.snap
  src/components/History/__test__/__snapshots__/Historycard.test.jsx.snap
  src/components/Home/Navbar.jsx
  src/components/aboutus/Teamcard.jsx
  src/components/meal/__test__/__snapshots__/mealbar.test.jsx.snap
  src/components/meal/__test__/__snapshots__/mealcard.test.jsx.snap
  src/components/meal/__test__/__snapshots__/meals.test.jsx.snap
  src/components/meal/__test__/__snapshots__/modal.test.jsx.snap
  src/components/meal/__test__/mealbar.test.jsx
  src/components/meal/__test__/mealcard.test.jsx
  src/components/meal/__test__/meals.test.jsx
  src/components/meal/__test__/modal.test.jsx
  src/components/meal/mealbar.jsx
  src/components/meal/mealcard.jsx
  src/components/meal/meals.jsx
  src/components/meal/modal.jsx
  src/pages/aboutus/index.jsx
  src/pages/api/create-payment-intent.js
  src/pages/cart/index.jsx
  src/pages/meals/index.jsx
Labels: page, component, style, test

#95 overview component
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Overview/__test__/__snapshots__/chartGraph.test.jsx.snap
  src/components/Overview/__test__/__snapshots__/overview.test.jsx.snap
  src/components/Overview/__test__/__snapshots__/statCard.test.jsx.snap
  src/components/Overview/__test__/__snapshots__/statCardList.test.jsx.snap
  src/components/Overview/__test__/chartGraph.test.jsx
  src/components/Overview/__test__/overview.test.jsx
  src/components/Overview/__test__/statCard.test.jsx
  src/components/Overview/__test__/statCardList.test.jsx
  src/components/Overview/chartGraph.jsx
  src/components/Overview/statCardList.jsx
Labels: page, component, test

#101 aboutus , meals page , history page
  package-lock.json
  package.json
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Cart/addToCartButton.jsx
  src/components/Cart/checkout.jsx
  src/components/History/Historycard.jsx
  src/components/History/__test__/__snapshots__/Adminhistory.test.jsx.snap
  src/components/History/__test__/__snapshots__/Historycard.test.jsx.snap
  src/components/Home/Navbar.jsx
  src/components/Home/__test__/__snapshots__/Navbar.test.jsx.snap
  src/components/Meals/addMeals.jsx
  src/components/Meals/mealsTable.jsx
  src/components/meal/Bar.jsx
  src/components/meal/__test__/__snapshots__/mealbar.test.jsx.snap
  src/components/meal/__test__/__snapshots__/mealcard.test.jsx.snap
  src/components/meal/__test__/__snapshots__/meals.test.jsx.snap
  src/components/meal/__test__/__snapshots__/modal.test.jsx.snap
  src/components/meal/mealbar.jsx
  src/components/meal/mealcard.jsx
  src/components/meal/meals.jsx
  src/components/meal/modal.jsx
  src/pages/_document.jsx
  src/pages/aboutus/index.jsx
  src/pages/meals/index.jsx
  tailwind.config.js
Labels: bug, page, component, style

#103 102 empty cart page
  public/images/cart/cart.png
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Auth/__test__/__snapshots__/resetPassword.test.js.snap
  src/components/Auth/__test__/__snapshots__/signIn.test.js.snap
  src/components/Auth/__test__/__snapshots__/signUp.test.js.snap
  src/components/Auth/__test__/resetPassword.test.js
  src/components/Auth/__test__/signIn.test.js
  src/components/Auth/__test__/signUp.test.js
  src/components/Auth/buttons/__test__/__snapshots__/googleSignInButton.test.js.snap
  src/components/Auth/buttons/__test__/__snapshots__/googleSignUpButton.test.js.snap
  src/components/Auth/buttons/__test__/googleSignInButton.test.js
  src/components/Auth/buttons/__test__/googleSignUpButton.test.js
  src/components/Auth/buttons/googleSignInButton.jsx
  src/components/Auth/buttons/googleSignUpButton.jsx
  src/components/Auth/resetPassword.jsx
  src/components/Auth/signIn.jsx
  src/components/Auth/signUp.jsx
  src/components/Cart/__test__/__snapshots__/addToCartButton.test.js.snap
  src/components/Cart/__test__/__snapshots__/card.test.js.snap
  src/components/Cart/__test__/__snapshots__/cartIcon.test.js.snap
  src/components/Cart/__test__/addToCartButton.test.js
  src/components/Cart/__test__/card.test.js
  src/components/Cart/__test__/cartIcon.test.js
  src/components/Cart/card.jsx
  src/components/Cart/cartIcon.jsx
  src/components/Email-template/email-template.jsx
  src/components/Settings/Settings.jsx
  src/components/Settings/__test__/Settings.test.js
  src/components/Settings/__test__/__snapshots__/Settings.test.js.snap
  src/components/Sidemenu.jsx
  src/pages/cart/index.jsx
  src/pages/signup/index.jsx
Labels: style, test

#106 57 modal
  public/gift.png
  public/trophy.png
  src/components/aboutus/Teamcard.jsx
  src/components/meal/Bar.jsx
  src/components/meal/CartContext.jsx
  src/components/meal/__test__/__snapshots__/meals.test.jsx.snap
  src/components/meal/meals.jsx
  src/pages/_document.jsx
  src/pages/aboutus/index.jsx
  tailwind.config.js
Labels: bug, component

#107 96 adjust blogs
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Blog/BlogCard/__test__/__snapshots__/blogCard.test.jsx.snap
  src/components/Blog/BlogCard/__test__/__snapshots__/blogCardList.test.jsx.snap
  src/components/Blog/BlogCard/__test__/blogCard.test.jsx
  src/components/Blog/BlogCard/__test__/blogCardList.test.jsx
  src/components/Blog/BlogCard/blogCard.jsx
  src/components/Blog/BlogCard/blogCardList.jsx
  src/components/Blog/StoryCard/__test__/__snapshots__/storyCard.test.jsx.snap
  src/components/Blog/StoryCard/__test__/__snapshots__/storyCardList.test.jsx.snap
  src/components/Blog/StoryCard/__test__/storyCard.test.jsx
  src/components/Blog/StoryCard/__test__/storyCardList.test.jsx
  src/components/Blog/StoryCard/storyCard.jsx
  src/components/Blog/StoryCard/storyCardList.jsx
  src/pages/blogs/blog/[blog].jsx
  src/pages/blogs/index.jsx
  src/pages/blogs/story/[story].jsx
Labels: page, component, data, style, test

#110 96 adjust blogs
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Blog/BlogCard/__test__/__snapshots__/blogCard.test.jsx.snap
  src/components/Blog/BlogCard/__test__/__snapshots__/blogCardList.test.jsx.snap
  src/components/Blog/BlogCard/blogCard.jsx
  src/pages/blogs/blog/[blog].jsx
  src/pages/blogs/story/[story].jsx
Labels: page, component, data, style

#112 96 adjust blogs
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Blog/BlogCard/__test__/__snapshots__/blogCard.test.jsx.snap
  src/components/Blog/BlogCard/__test__/__snapshots__/blogCardList.test.jsx.snap
  src/components/Blog/BlogCard/blogCard.jsx
  src/components/Blog/BlogCard/blogCardList.jsx
  src/components/Blog/StoryCard/__test__/__snapshots__/storyCard.test.jsx.snap
  src/components/Blog/StoryCard/__test__/__snapshots__/storyCardList.test.jsx.snap
  src/components/Blog/StoryCard/storyCard.jsx
  src/components/Meals/addMeals.jsx
  src/components/Meals/mealsTable.jsx
  src/components/Overview/__test__/__snapshots__/chartGraph.test.jsx.snap
  src/components/Overview/__test__/__snapshots__/overview.test.jsx.snap
  src/components/Overview/__test__/__snapshots__/statCard.test.jsx.snap
  src/components/Overview/__test__/__snapshots__/statCardList.test.jsx.snap
  src/components/Overview/chartGraph.jsx
  src/components/Overview/overview.jsx
  src/components/Overview/statCard.jsx
  src/components/Overview/statCardList.jsx
  src/pages/blogs/blog/[blog].jsx
  src/pages/blogs/index.jsx
Labels: bug, page, component, style

#117 Translation & styling
  README.md
  next-i18next.config.js
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/Cart/__test__/__snapshots__/addToCartButton.test.js.snap
  src/components/Cart/addToCartButton.jsx
  src/components/Cart/checkout.jsx
  src/components/History/Historycard.jsx
  src/components/History/__test__/__snapshots__/Adminhistory.test.jsx.snap
  src/components/History/__test__/__snapshots__/Historycard.test.jsx.snap
  src/components/Home/Navbar.jsx
  src/components/Home/__test__/__snapshots__/Navbar.test.jsx.snap
  src/components/aboutus/__test__/Teamcard.test.jsx
  src/components/aboutus/__test__/__snapshots__/Teamcard.test.jsx.snap
  src/components/meal/CartContext.jsx
  src/components/meal/__test__/__snapshots__/mealbar.test.jsx.snap
  src/components/meal/mealbar.jsx
  src/components/meal/modal.jsx
  src/util/i18n.js
Labels: feature, component, style

#120 translation & styling
  README.md
  public/locales/fr/common.json
  src/components/Cart/checkout.jsx
  src/components/Sidemenu.jsx
Labels: feature, component, style

#124 115 adjust functions
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Cart/card.jsx
  src/components/History/Historycard.jsx
  src/components/Home/Goals.jsx
  src/components/Home/Joinus.jsx
  src/components/Home/Restaurant.jsx
  src/components/Home/Sponsors.jsx
  src/components/Home/__test__/__snapshots__/Goals.test.jsx.snap
  src/components/Home/__test__/__snapshots__/Joinus.test.jsx.snap
  src/components/Home/__test__/__snapshots__/Restaurant.test.jsx.snap
  src/components/Home/__test__/__snapshots__/Sponsors.test.jsx.snap
  src/components/Meals/__test__/__snapshots__/addMeals.test.js.snap
  src/components/Meals/__test__/__snapshots__/mealsTable.test.js.snap
  src/components/Meals/mealsTable.jsx
  src/components/Overview/chartGraph.jsx
  src/components/Settings/Settings.jsx
  src/components/meal/__test__/__snapshots__/mealcard.test.jsx.snap
  src/components/meal/mealcard.jsx
  src/pages/admin-dashboard/index.js
Labels: bug

#125 105 404 page
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/Cart/cartIcon.jsx
  src/components/Email-template/__test__/__snapshots__/email-template.test.js.snap
  src/components/Email-template/__test__/email-template.test.js
  src/components/Settings/Settings.jsx
  src/components/Sidemenu.jsx
Labels: bug, style

#126 57 modal
  public/locales/fr/common.json
  src/components/Cart/checkout.jsx
  src/components/History/Adminhistory.jsx
  src/components/History/Historycard.jsx
  src/components/History/__test__/__snapshots__/Adminhistory.test.jsx.snap
  src/components/History/__test__/__snapshots__/Historycard.test.jsx.snap
  src/components/meal/__test__/__snapshots__/mealbar.test.jsx.snap
  src/components/meal/__test__/__snapshots__/mealcard.test.jsx.snap
  src/components/meal/__test__/__snapshots__/modal.test.jsx.snap
  src/components/meal/mealbar.jsx
  src/components/meal/mealcard.jsx
  src/components/meal/meals.jsx
  src/components/meal/modal.jsx
Labels: component, style
