Repository 202306-NEA-DZ-FEW/Capstone-Dream-Team, pull requests merged in 2023-10, with the labels that each got.

#7 feat: add Firebase Integration (closes #6)
  .gitignore
  package-lock.json
  package.json
  src/util/firebase.js
Labels: integration

#17 style: integrate Tailwind CSS into the project (closes #16)
  package-lock.json
  package.json
  src/styles/globals.css
  tailwind.config.js
Labels: integration

#26 2 sign insign up page
  .gitignore
  package-lock.json
  package.json
  src/components/Auth/resetPassword.jsx
  src/components/Auth/signIn.jsx
  src/components/Auth/signOut.jsx
  src/components/Auth/signUp.jsx
Labels: feature, integration, component

#30 fix(sidemenu): fixed bug related to the sidemenu not showing on the page
  src/components/Sidemenu.jsx
Labels: bug

#31 fix(sidemenu): fix a bug related to the presentation of user information within the sidemenu
  src/components/Sidemenu.jsx
Labels: bug

#33 2 sign insign up page
  .prettierignore
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Auth/buttons/googleSignInButton.jsx
  src/components/Auth/buttons/googleSignUpButton.jsx
  src/components/Auth/resetPassword.jsx
  src/components/Auth/signIn.jsx
  src/components/Auth/signOut.jsx
  src/components/Auth/signUp.jsx
  src/layout/Layout.jsx
  src/pages/_document.jsx
  src/pages/index.jsx
  src/pages/signup/index.jsx
Labels: feature, integration, page, component

#32 feat: adjust the fetching of the data from the firebase collection (D…
  src/components/Adminhistory.jsx
  src/components/Historycard.jsx
Labels: component

#36 feat(overview component): add statCardList and line Chart components
  package-lock.json
  package.json
  src/components/Overview/lineChart.jsx
  src/components/Overview/overview.jsx
  src/components/Overview/statCard.jsx
  src/components/Overview/statCardList.jsx
Labels: feature, component

#39 feat(adding navbar and optimizing sidemenu code):
  public/images/darklogo.svg
  public/images/darklogoName.svg
  public/images/docs-left.png
  public/images/docs-right.png
  public/images/logo.svg
  public/images/logoName.svg
  public/images/placeholderImage.png
  src/components/Dashboard.jsx
  src/components/History/Adminhistory.jsx
  src/components/History/History.jsx
  src/components/History/Historybar.jsx
  src/components/History/Historycard.jsx
  src/components/Navbar.jsx
  src/components/Overview/Dashboard.jsx
  src/components/Sidemenu.jsx
  src/images/placeholderImage.png
  src/layout/Layout.jsx
  src/pages/admin-dashboard/index.js
Labels: component, Medium

#40 feat(navbar): adding a dropdown list with an icon of user to the navbar
  src/components/Navbar.jsx
Labels: feature

#41 feat: created the meals page and all the data is fetched from the fai…
  src/components/History/Adminhistory.jsx
  src/components/History/Historycard.jsx
  src/components/meal/mealbar.jsx
  src/components/meal/mealcard.jsx
  src/pages/meals/index.jsx
Labels: page, component, hard

#42 feat: i have changed the method for fetching
  src/pages/meals/index.jsx
Labels: bug, page, Medium

#43 feat(navbar sidemenu index): adding language button and responsiveness to the navbar
  src/components/Dashboard.jsx
  src/components/Navbar.jsx
  src/components/Sidemenu.jsx
  src/layout/Layout.jsx
  src/pages/admin-dashboard/index.js
  src/pages/index.jsx
Labels: feature

#44 11 cart page
  package-lock.json
  package.json
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Auth/signUp.jsx
  src/components/Cart/addToCartButton.jsx
  src/components/Cart/card.jsx
  src/components/Cart/cartIcon.jsx
  src/pages/cart/index.jsx
  src/pages/index.jsx
Labels: feature, page, component

#45 35 story component
  public/images/fatoom_in_yemen.png
  src/components/Blog/Story Card/StoryCard.jsx
  src/components/Blog/Story Card/StoryCardList.jsx
  src/util/newsApi.js
Labels: feature, component

#50 feat(slider): add a slider to home page
  public/images/home/slider/image1.jpg
  public/images/home/slider/image2.jpg
  public/images/home/slider/image3.jpg
  src/components/Home/Navbar.jsx
  src/components/Home/Slider.jsx
Labels: component

#51 4 meals page
  public/gift.png
  public/images/meals/bolognese-sauce-pasta-salad-italian-cuisine-spaghetti-cooking-thumbnail.jpg
  public/images/meals/italian-cuisine-pasta-organic-food-restaurant-foods.jpg
  public/trophy.png
  src/components/meal/mealbar.jsx
  src/components/meal/mealcard.jsx
  src/components/meal/meals.jsx
  src/components/meal/modal.jsx
  src/pages/meals/index.jsx
Labels: page, component

#55 feat(blogs page): add blogs and blog pages
  src/pages/blogs/[blog].jsx
  src/pages/blogs/index.jsx
  src/util/newsApi.js
Labels: feature, page

#54 feat(blog card): add blog card and blog card list
  src/components/Blog/Blog Card/BlogCard.jsx
  src/components/Blog/Blog Card/BlogCardList.jsx
Labels: feature, component

#53 feat(article component): add article component
  src/components/Article/article.jsx
Labels: feature, component

#58 feat: add modal for the restaurant's meals
  src/components/Home/Navbar.jsx
  src/components/meal/mealbar.jsx
  src/components/meal/meals.jsx
  src/components/meal/modal.jsx
  src/pages/meals/index.jsx
Labels: feature, component, data

#60 feat(bug): finished with the responsivness of the meals grid
  src/components/meal/mealbar.jsx
  src/components/meal/meals.jsx
  src/components/meal/modal.jsx
Labels: bug

#62 feat(blog page): add translation and tests
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Blog/BlogCard/blogCard.jsx
  src/components/Blog/BlogCard/blogCardList.jsx
  src/components/Blog/Story Card/StoryCard.jsx
  src/components/Blog/Story Card/StoryCardList.jsx
  src/components/Blog/StoryCard/__test__/__snapshots__/storyCard.test.jsx.snap
  src/components/Blog/StoryCard/__test__/__snapshots__/storyCardList.test.jsx.snap
  src/components/Blog/StoryCard/__test__/storyCard.test.jsx
  src/components/Blog/StoryCard/__test__/storyCardList.test.jsx
  src/components/Blog/StoryCard/storyCard.jsx
  src/components/Blog/StoryCard/storyCardList.jsx
  src/pages/blogs/index.jsx
  src/util/i18n.js
Labels: feature, page, component

#63 57 modal
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/History/Historycard.jsx
  src/components/meal/mealcard.jsx
  src/components/meal/modal.jsx
  src/pages/meals/index.jsx
Labels: feature

#64 56 settings
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/Auth/__test__/__snapshots__/signUp.test.js.snap
  src/components/Auth/__test__/signUp.test.js
  src/components/Auth/signUp.jsx
  src/components/Settings.jsx
Labels: component, data
